### ISSUE TITLE
12306 余票查询api

### ISSUE THREAD

**Issue by AsherYang** [jokermonn/-Api#1]
首先感谢提供如此详细的api福利。
今天(2017-03-15)试了一下，余票查询api:
url：https://kyfw.12306.cn/otn/leftTicket/queryZ 无法正常使用，多了最后一个字母Z，（看url实例中也是如此）
操作结果应为：https://kyfw.12306.cn/otn/leftTicket/query 可以使用（抓包查到），不知是12306改了还是什么情况~

**Comment by jokermonn** [comment]
经测试，12306更改了 api 接口，利用原始接口 https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2017-03-15&leftTicketDTO.from_station=BJP&leftTicketDTO.to_station=SHH&purpose_codes=0X00。返回的数据可以看到有一个 `c_url` 字段，其值为 `leftTicket/query`。将 https://kyfw.12306.cn/otn/ 添上 `c_url` 字段的值就可以了。web 端就是这样，api 接口随时可以更改所以不便获取，移动端一般就不会有这样的问题了。感谢反馈

**Comment by AsherYang** [comment]
嗯。是的，期待更多接口放送。
