### ISSUE TITLE
很喜欢你的API,可否抓取一个APP的接口

### ISSUE THREAD

**Issue by cm971991** [jokermonn/-Api#11]
有一个APP叫虎扑体育 能否抓取下 或者教下如何抓取 谢了

**Comment by jokermonn** [comment]
百度一下 fiddler，用它抓就可以了

**Comment by cm971991** [comment]
我想抓的是安卓app端的数据 不知道如何搞

**Comment by jokermonn** [comment]
电脑开 fiddler，然后开热点给移动端，抓包就行了，百度 fiddler 用法

**Comment by cm971991** [comment]
好的谢啦

**Comment by cm971991** [comment]
大神 有个问题想请教下 我用fiddler抓包手机APP成功了 但是发现其中有个请求字段加密 不知道如何解密 求教
_sig=iMcoZC5v7OjD83MhjvYIV0DX5p0%3D
_sig=kQo%2BzxgUT4CrdwOziKZVU1GRVyM%3D
