### ISSUE TITLE
CenterWeatherCityCode JSON数据中，城市 新西兰 少了cityEN 字段

### ISSUE THREAD

**Issue by hpu-spring87** [jokermonn/-Api#13]
第3438-3444之间数据，少了cityEN 字段：

{
    "ID": "3439",
    "cityName": "新西兰",
    "townID": "NZXX000000",
    "townName": "惠灵顿",
    "townEN": "Wellington"
}

**Comment by jokermonn** [comment]
![image](https://user-images.githubusercontent.com/16160722/28782645-580eff86-7640-11e7-98c0-f6e594250fb4.png)
似乎就是没有这个字段
