### ISSUE TITLE
请求次数限制问题

### ISSUE THREAD

**Issue by kandra777** [jokermonn/-Api#15]
你好 首先感谢作者提供这么好的一个收集的文章.我自己有个app是视频相关的 像尝试获取豆瓣电影的api里面的剧照和演员信息 .但是我看官网 是通过key来区分了版本的 如果是基础key的话 每个小时好想是限制了访问次数的 不知道作者提供的这个key有没有这个限制.

**Comment by jokermonn** [comment]
这是官方应用的 key，应该是没有限制的

**Comment by kandra777** [comment]
多谢
