### ISSUE TITLE
开眼api

### ISSUE THREAD

**Issue by Zweihui** [jokermonn/-Api#18]
比如我想获取分类里的创意的数据，http://baobab.kaiyanapp.com/api/v4/category/2/?title=创意 ， URL是这么拼吗？现在返回{"errorCode":404,"errorMessage":"Resource Not Found"}

**Comment by mTerminal** [comment]
我的是去年 v3 的版本。
http://baobab.wandoujia.com/api/v3/videos?&categoryId=36

**Comment by Zweihui** [comment]
原来官方app的数据就可以抓了- -，还是自己去抓最新的吧
