### ISSUE TITLE
2017年9月9日接口又更新了

### ISSUE THREAD

**Issue by zxfsadly** [jokermonn/-Api#22]
余票查询api接口又换了
{"status":false,"c_url":"leftTicket/queryX","c_name":"CLeftTicketUrl"}，
余票查询api:
之前url：https://kyfw.12306.cn/otn/leftTicket/query 
现在正确的url：https://kyfw.12306.cn/otn/leftTicket/queryX

**Comment by jokermonn** [comment]
感谢您的反馈，回复较慢，抱歉

**Comment by zxfsadly** [comment]
是不是现在要在linux上安装https证书才可以获取数据啊，我之前不用安装也可以获取，现在获取不到

**Comment by AndsoonCode** [comment]
http://ww3.sinaimg.cn/large/0060lm7Tly1fjjh6qozgyj31hc0pcgol.jpg
请问这种数据怎么解析

**Comment by zxfsadly** [comment]
这是我写的计算票价和显示站点的php程序

发送自 Windows 10 版邮件应用

发件人: AndsoonCode
发送时间: 2017年9月14日 22:48
收件人: jokermonn/-Api
抄送: zxfsadly; Author
主题: Re: [jokermonn/-Api] 2017年9月9日接口又更新了 (#22)

http://ww3.sinaimg.cn/large/0060lm7Tly1fjjh6qozgyj31hc0pcgol.jpg
请问这种数据怎么解析

**Comment by jokermonn** [comment]
@zxfsadly :thumbsup:
