### ISSUE TITLE
开眼那个api返回数据说将要停止使用

### ISSUE THREAD

**Issue by shimangdian** [jokermonn/-Api#4]
word哥，意思是不能用还是不会更新了？

**Comment by jokermonn** [comment]
哪一个？放个链接上来，我点了几个没看到

**Comment by shimangdian** [comment]
https://baobab.kaiyanapp.com/api/v4/tabs/selected   这个api里面的第一个object的图片
http://img.kaiyanapp.com/2785576637a7b9fd836396fb6dc78b26.jpeg?imageMogr2/quality/60/format/jpg

**Comment by jokermonn** [comment]
它客户端要更新了，至于这个接口维不维护我不知道
