### ISSUE TITLE
中国天气预报的天气图标怎么获取？

### ISSUE THREAD

**Issue by chrissen0814** [jokermonn/-Api#5]
根据中国天气预报的api获取到的数据中，有一个天气code，我想获取到它的图标？怎么做

**Comment by jokermonn** [comment]
具体点，哪个API

**Comment by chrissen0814** [comment]
这是用中国天气预报api获取到的数据
"weather": [
    {
      "city_name": "佛山",
      "city_id": "CHGD070000",
      "last_update": "2017-02-19T12:15:00+08:00",
      "now": {
        "text": "阴",
        "code": "9",

在now中不是有一个code ，应该可以通过这个code获取到对应的天气状况图标吧。

**Comment by jokermonn** [comment]
这是我这里面的 api 么

**Comment by jokermonn** [comment]
我看了一下，当时我解析的时候就不知道 code 字段是干什么的

**Comment by chrissen0814** [comment]
应该是用来获取对应text中的天气图标的，我猜
