### ISSUE TITLE
老哥你这车稳吗？我看豆瓣电影那个APIkey感觉会不会翻车啊。。

### ISSUE THREAD

**Issue by ouzhou** [jokermonn/-Api#7]
-。- 好奇这个APIkey是怎么弄到的。我尝试申请了，结果这个狗日的豆瓣不对个人用户开放

**Comment by jokermonn** [comment]
豆瓣电影的官方 App 已经多年没更新了，界面还停留在2.0-4.0的时代，估计这个 App 官方已经废弃了，Api Key 就是这个官方 App 的 key，稳不稳自己体会
