### ISSUE TITLE
各种跨域都没能解决啊

### ISSUE THREAD

**Issue by abaozhizhong** [jokermonn/-Api#8]
跨域获取不了json 数据呀

**Comment by jokermonn** [comment]
没太懂你的意思

**Comment by abaozhizhong** [comment]
//douban 
   $.ajax({
        type:"get",
        url:"https://api.douban.com/v2/movie/in_theaters?apikey=0b2bdeda43b5688921839c8ecb20399b&city=%E5%8C%97%E4%BA%AC&start=0&count=100&client=&udid=",
        dataType:"jsonp",
        success:function (data) {
            console.log(data);
        }
    })

//   mtime
    $.ajax({
        type:"get",
        url:"https://api-m.mtime.cn/Showtime/HotCitiesByCinema.api",
        dataType:"jsonp",
        success:function (data) {
            console.log(data);  // 这里报 Uncaught SyntaxError: Unexpected token :
        }
    })

**Comment by jokermonn** [comment]
mtime 的添加请求头：Host:api-m.mtime.cn。至于前一个，我没测试出啥问题，估计也就是请求头没有添加上，你可以用浏览器调试一下，然后添加相应的请求头，欢迎反馈

**Comment by abaozhizhong** [comment]
好的谢谢您
